version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  except:
  - ci/travis
skip_commits:
  message: /Merge tag.*into develop/
  files:
    - '*.md'
    - LICENSE
    - .travis.yml
image:
- Visual Studio 2017
- Ubuntu
cache: tools -> setup.cake,.appveyor.yml,setup.cake
install:
- cmd: cinst python3 -n
- cmd: cinst transifex-client
- sh: sudo -H pip install transifex-client
build_script:
- pwsh: |
    if ($isLinux) {
        .\build.ps1 --configuration=Release --target=AppVeyor-Linux
    } else {
        .\build.ps1 --configuration=Release --target=AppVeyor
    }
test: off
deploy: off
