version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
skip_commits:
  message: /Merge tag.*into develop/
  files:
    - '*.md'
    - LICENSE
    - .travis.yml
image:
- Visual Studio 2017
- Ubuntu
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
cache: tools -> setup.cake,.appveyor.yml,build.config
install:
- cmd: cinst python3 -n
- cmd: cinst transifex-client
- sh: sudo -H pip install transifex-client
- sh: sudo apt-get update && sudo apt-get install -y libgit2-dev
build_script:
- ps: .\build.ps1 --configuration=Release --target=AppVeyor
- sh: ./build.sh --configuration=Release --target=AppVeyor-Linux
test: off
deploy: off
