image:
  #    - macos
  - Ubuntu
  - Visual Studio 2017
matrix:
  fast_finish: true
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
branches:
  except:
    - ci/travis
    - /dependabot\/.*/
skip_commits:
  files:
    - "*.md"
    - "LICENSE"
    - ".travis.yml"

for:
-
  matrix:
    only:
      - image: Ubuntu
  skip_tags: true
  install:
    - git submodule update --init
    - sudo -H pip install transifex-client
    - sudo apt-get update || echo "Update failed, ignoring..."
    - sudo apt-get install -y libgit2-dev

install:
  - git submodule update --init
  - cmd: |
      cinst python3 -n
      cinst transifex-client

build: off
test: off

build_script:
  - pwsh: ./build.ps1 --target=ContinuousIntegration --verbosity=Diagnostic

cache:
  - "tools -> build.config,setup.cake,.build/sonarcloud.cake"
  - ".dotnet -> build.config"
