pull_request_rules:
  - name: Add docs labes for documentation change
    conditions:
      - "files~=^docs/.*"
    actions:
      label:
        add: ["Documentation"]
  - name: Merge PR when ci passes and 1 approved review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=Travis CI - Pull Request
      - status-success=continuous-integration/appveyor/pr
    actions:
      delete_head_branch:
      merge:
        strict: smart
        strict_method: rebase
