language: csharp
dist: xenial
os:
  - linux
  - osx
mono: latest
dotnet: 2.1.603

branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/
    - ci/appveyor

cache:
  directories:
    - tools

addons:
  apt:
    packages:
      - transifex-client
  homebrew:
    packages:
      - python
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
git:
  depth: false

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then pip install transifex-client; fi

script:
  - ./build.sh --target=Linux
